/**
 * ─── Pharmacy + Lab Pages ────────────────────────────────────
 * Metadata-driven — all labels from entity packages.
 */
import React, { useEffect, useState } from 'react'
import { Link, useParams, useNavigate } from '@tanstack/react-router'
import { Card, CardHeader, CardContent, cn } from '@repo/ui-core'
import { pharmacyRepo, labRepo } from '../../lib/db'
import { PHARMACY_ORDER_STATUS_LABELS, PHARMACY_ORDER_TYPE_LABELS } from '@repo/entity-pharmacy'
import { LAB_ORDER_STATUS_LABELS, LAB_ORDER_PRIORITY_LABELS, LAB_CATEGORY_LABELS } from '@repo/entity-laboratory'
import { Plus, Search, ArrowLeft, Save, PillBottle, Microscope } from 'lucide-react'

const TENANT_ID = 'default-tenant'

// ─── Pharmacy List ───────────────────────────────────────────
export function PharmacyListPage() {
  const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true)
  useEffect(()=>{pharmacyRepo.findMany({limit:100}).then((r:any)=>{setItems('items' in r?r.items:[]);setLoading(false)}).catch(()=>setLoading(false))},[])
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Pharmacy</h1><p className="text-sm text-gray-500">{items.length} orders</p></div><Link to="/pharmacy/new" className="inline-flex items-center gap-2 rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700"><Plus className="h-4 w-4"/>New Order</Link></div>
  {loading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-16 animate-pulse rounded-lg bg-gray-100"/>)}</div>
  :<div className="rounded-lg border bg-white"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr>{['Type','Patient','Items','Status','Date'].map(l=><th key={l} className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">{l}</th>)}</tr></thead><tbody className="divide-y divide-gray-200">{items.map((r:any)=>(<tr key={r.id} className="cursor-pointer hover:bg-gray-50" onClick={()=>window.location.href=`/pharmacy/${r.id}`}><td className="px-4 py-3 text-sm">{PHARMACY_ORDER_TYPE_LABELS[r.type]??r.type}</td><td className="px-4 py-3 text-sm text-gray-600">{r.patientId?.slice(0,8)}...</td><td className="px-4 py-3 text-sm text-gray-600">{r.items?.map((i:any)=>i.medicationName).join(', ').slice(0,60)}</td><td className="px-4 py-3 text-sm"><span className={cn('rounded-full px-2 py-0.5 text-xs font-medium',r.status==='dispensed'?'bg-green-100 text-green-800':r.status==='ready'?'bg-blue-100 text-blue-800':'bg-gray-100 text-gray-800')}>{PHARMACY_ORDER_STATUS_LABELS[r.status]??r.status}</span></td><td className="px-4 py-3 text-sm text-gray-600">{r.receivedAt?new Date(r.receivedAt).toLocaleDateString():'-'}</td></tr>))}</tbody></table></div>}</div>)
}

export function CreatePharmacyOrderPage() {
  const navigate = useNavigate(); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
  const [form,setForm]=useState<Record<string,unknown>>({patientId:'',type:'prescription',items:'[{"id":"1","inventoryItemId":"","medicationName":"Paracetamol 500mg","strength":"500mg","quantity":20,"unitPrice":2.50,"isControlled":false}]',instructions:'',notes:''})
  const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setSaving(true)
    try{let items;try{items=JSON.parse(form.items as string)}catch{items=[{id:'1',inventoryItemId:'',medicationName:form.items,strength:'',quantity:1,unitPrice:0}]}
    const r=await pharmacyRepo.create({tenantId:TENANT_ID,patientId:form.patientId,type:form.type,items,instructions:form.instructions,notes:form.notes} as any)
    navigate({to:'/pharmacy/$id',params:{id:r.id}})}catch(err:any){setError(err.message)}finally{setSaving(false)}}
  return (<div className="p-6"><div className="mb-6 flex items-center gap-4"><button onClick={()=>navigate({to:'/pharmacy'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">New Pharmacy Order</h1></div></div>{error&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <form onSubmit={handleSubmit}><Card><CardContent><div className="grid grid-cols-1 gap-4 md:grid-cols-2">
    {[{name:'patientId',label:'Patient ID',type:'text',required:true},{name:'type',label:'Type',type:'select',options:[{label:'Prescription',value:'prescription'},{label:'OTC Sale',value:'otc_sale'},{label:'Refill',value:'refill'},{label:'Compounding',value:'compounding'}]},{name:'items',label:'Items (JSON)',type:'textarea',required:true,helper:'[{"id":"1","medicationName":"...","strength":"...","quantity":1,"unitPrice":0,"isControlled":false}]'},{name:'instructions',label:'Instructions',type:'text'},{name:'notes',label:'Notes',type:'textarea'}].map(f=>(<div key={f.name} className={(f.name==='items'||f.name==='notes')?'col-span-full space-y-1':'space-y-1'}><label className="block text-sm font-medium text-gray-700">{f.label}{f.required&&<span className="text-red-500 ml-1">*</span>}</label>{f.type==='select'?<select value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"><option value="">Select...</option>{f.options?.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} rows={4} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm font-mono"/>:<input type={f.type} value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"/>}{(f as any).helper&&<p className="text-xs text-gray-500">{(f as any).helper}</p>}</div>))}
  </div></CardContent></Card><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>navigate({to:'/pharmacy'})} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700 disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving...':'Save Order'}</button></div></form></div>)
}

export function PharmacyOrderDetailPage() {
  const { id } = useParams({ from: '/pharmacy/$id' }); const navigate = useNavigate(); const [data,setData]=useState<any>(null)
  useEffect(()=>{pharmacyRepo.findById(id).then(setData).catch(console.error)},[id])
  if(!data) return <div className="flex h-full items-center justify-center"><div className="text-center"><PillBottle className="mx-auto h-12 w-12 text-gray-300"/><h2 className="text-2xl font-semibold mt-2">Order Not Found</h2><button onClick={()=>navigate({to:'/pharmacy'})} className="mt-4 rounded-lg bg-green-600 px-4 py-2 text-sm text-white">Back</button></div></div>
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-4"><button onClick={()=>navigate({to:'/pharmacy'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">{PHARMACY_ORDER_TYPE_LABELS[data.type]??data.type}</h1><p className="text-sm text-gray-500">{data.receivedAt?new Date(data.receivedAt).toLocaleString():''}</p></div></div><span className={cn('rounded-full px-3 py-1 text-xs font-medium',data.status==='dispensed'?'bg-green-100 text-green-800':'bg-blue-100 text-blue-800')}>{PHARMACY_ORDER_STATUS_LABELS[data.status]??data.status}</span></div>
  <Card><CardHeader title="Items"/><CardContent>{data.items?.map((item:any,i:number)=>(<div key={i} className="flex justify-between py-2 border-b last:border-0"><div><p className="text-sm font-medium">{item.medicationName} {item.strength}</p>{item.sigInstructions&&<p className="text-xs text-gray-500">{item.sigInstructions}</p>}</div><div className="text-right"><p className="text-sm font-medium">Qty: {item.quantity}</p><p className="text-sm">${item.unitPrice?.toLocaleString?.()??item.unitPrice} ea</p>{item.isControlled&&<span className="text-xs text-red-600">Controlled</span>}</div></div>))}</CardContent></Card>
  <div className="mt-4 grid grid-cols-2 gap-4"><Card><CardHeader title="Totals"/><CardContent><p className="text-sm">Total: ${data.totalCost?.toLocaleString?.()??data.totalCost}</p><p className="text-sm">Insurance: ${data.insuranceCoverage?.toLocaleString?.()??data.insuranceCoverage}</p><p className="text-sm font-semibold">Patient Pay: ${data.patientPay?.toLocaleString?.()??data.patientPay}</p></CardContent></Card><Card><CardHeader title="Details"/><CardContent className="text-sm space-y-1"><p>Status: {PHARMACY_ORDER_STATUS_LABELS[data.status]??data.status}</p>{data.instructions&&<p>Instructions: {data.instructions}</p>}{data.processedBy&&<p>Processed by: {data.processedBy}</p>}</CardContent></Card></div></div>)
}

// ─── Lab List ────────────────────────────────────────────────
export function LabListPage() {
  const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true)
  useEffect(()=>{labRepo.findMany({limit:100}).then((r:any)=>{setItems('items' in r?r.items:[]);setLoading(false)}).catch(()=>setLoading(false))},[])
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Laboratory</h1><p className="text-sm text-gray-500">{items.length} orders</p></div><Link to="/laboratory/new" className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"><Plus className="h-4 w-4"/>New Lab Order</Link></div>
  {loading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-16 animate-pulse rounded-lg bg-gray-100"/>)}</div>
  :<div className="rounded-lg border bg-white"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr>{['Priority','Patient','Tests','Status','Ordered'].map(l=><th key={l} className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">{l}</th>)}</tr></thead><tbody className="divide-y divide-gray-200">{items.map((r:any)=>(<tr key={r.id} className="cursor-pointer hover:bg-gray-50" onClick={()=>window.location.href=`/laboratory/${r.id}`}><td className="px-4 py-3 text-sm"><span className={cn('rounded-full px-2 py-0.5 text-xs font-medium',r.priority==='stat'?'bg-red-100 text-red-800':r.priority==='urgent'?'bg-yellow-100 text-yellow-800':'bg-blue-100 text-blue-800')}>{LAB_ORDER_PRIORITY_LABELS[r.priority]??r.priority}</span></td><td className="px-4 py-3 text-sm text-gray-600">{r.patientId?.slice(0,8)}...</td><td className="px-4 py-3 text-sm text-gray-600">{r.tests?.map((t:any)=>t.testName).join(', ').slice(0,60)}</td><td className="px-4 py-3 text-sm">{LAB_ORDER_STATUS_LABELS[r.status]??r.status}</td><td className="px-4 py-3 text-sm text-gray-600">{r.orderedAt?new Date(r.orderedAt).toLocaleDateString():'-'}</td></tr>))}</tbody></table></div>}</div>)
}

export function CreateLabOrderPage() {
  const navigate = useNavigate(); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
  const [form,setForm]=useState<Record<string,unknown>>({patientId:'',doctorId:'',priority:'routine',tests:'[{"id":"1","testCode":"CBC","testName":"Complete Blood Count","category":"hematology","specimenType":"blood"}]',clinicalReason:'',notes:''})
  const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setSaving(true)
    try{let tests;try{tests=JSON.parse(form.tests as string)}catch{tests=[{id:'1',testCode:'GENERIC',testName:form.tests,category:'other',specimenType:'blood'}]}
    const r=await labRepo.create({tenantId:TENANT_ID,patientId:form.patientId,doctorId:form.doctorId,priority:form.priority,tests,clinicalReason:form.clinicalReason,notes:form.notes} as any)
    navigate({to:'/laboratory/$id',params:{id:r.id}})}catch(err:any){setError(err.message)}finally{setSaving(false)}}
  return (<div className="p-6"><div className="mb-6 flex items-center gap-4"><button onClick={()=>navigate({to:'/laboratory'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">New Lab Order</h1></div></div>{error&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <form onSubmit={handleSubmit}><Card><CardContent><div className="grid grid-cols-1 gap-4 md:grid-cols-2">
    {[{name:'patientId',label:'Patient ID',type:'text',required:true},{name:'doctorId',label:'Doctor ID',type:'text',required:true},{name:'priority',label:'Priority',type:'select',options:[{label:'Routine',value:'routine'},{label:'Urgent',value:'urgent'},{label:'STAT',value:'stat'}]},{name:'clinicalReason',label:'Clinical Reason',type:'text'},{name:'tests',label:'Tests (JSON)',type:'textarea',required:true,helper:'[{"id":"1","testCode":"CBC","testName":"Complete Blood Count","category":"hematology","specimenType":"blood"}]'},{name:'notes',label:'Notes',type:'textarea'}].map(f=>(<div key={f.name} className={(f.name==='tests'||f.name==='notes')?'col-span-full space-y-1':'space-y-1'}><label className="block text-sm font-medium text-gray-700">{f.label}{f.required&&<span className="text-red-500 ml-1">*</span>}</label>{f.type==='select'?<select value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"><option value="">Select...</option>{f.options?.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} rows={4} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm font-mono"/>:<input type={f.type} value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"/>}{(f as any).helper&&<p className="text-xs text-gray-500">{(f as any).helper}</p>}</div>))}
  </div></CardContent></Card><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>navigate({to:'/laboratory'})} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving...':'Save Lab Order'}</button></div></form></div>)
}

export function LabOrderDetailPage() {
  const { id } = useParams({ from: '/laboratory/$id' }); const navigate = useNavigate(); const [data,setData]=useState<any>(null)
  useEffect(()=>{labRepo.findById(id).then(setData).catch(console.error)},[id])
  if(!data) return <div className="flex h-full items-center justify-center"><div className="text-center"><Microscope className="mx-auto h-12 w-12 text-gray-300"/><h2 className="text-2xl font-semibold mt-2">Order Not Found</h2><button onClick={()=>navigate({to:'/laboratory'})} className="mt-4 rounded-lg bg-blue-600 px-4 py-2 text-sm text-white">Back</button></div></div>
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-4"><button onClick={()=>navigate({to:'/laboratory'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">Lab Order</h1><p className="text-sm text-gray-500">{data.orderedAt?new Date(data.orderedAt).toLocaleString():''} · {LAB_ORDER_PRIORITY_LABELS[data.priority]??data.priority}</p></div></div><span className={cn('rounded-full px-3 py-1 text-xs font-medium',data.status==='completed'?'bg-green-100 text-green-800':'bg-blue-100 text-blue-800')}>{LAB_ORDER_STATUS_LABELS[data.status]??data.status}</span></div>
  <Card><CardHeader title="Tests"/><CardContent>{data.tests?.map((t:any,i:number)=>(<div key={i} className="flex justify-between py-2 border-b last:border-0"><div><p className="text-sm font-medium">{t.testName} <span className="text-xs text-gray-400">({t.testCode})</span></p><p className="text-xs text-gray-500">{LAB_CATEGORY_LABELS[t.category]??t.category} · {t.specimenType}</p></div><span className={cn('text-xs rounded-full px-2 py-0.5',t.status==='completed'?'bg-green-100 text-green-700':'bg-gray-100 text-gray-600')}>{t.status}</span></div>))}</CardContent></Card>
  {data.results?.length>0&&<Card className="mt-4"><CardHeader title="Results"/><CardContent>{data.results.map((r:any,i:number)=>(<div key={i} className="flex justify-between py-2 border-b last:border-0"><div><p className="text-sm font-medium">{r.testName}</p><p className="text-xs text-gray-500">{r.value} {r.unit} {r.referenceRange?`(Ref: ${r.referenceRange})`:''}</p></div>{r.isAbnormal&&<span className={cn('text-xs rounded-full px-2 py-0.5 font-medium',r.abnormalFlag==='LL'||r.abnormalFlag==='HH'?'bg-red-100 text-red-700':'bg-yellow-100 text-yellow-700')}>{r.abnormalFlag??'Abnormal'}</span>}</div>))}</CardContent></Card>}
  <Card className="mt-4"><CardHeader title="Sample"/><CardContent className="text-sm">{data.sample?<div className="space-y-1"><p>Sample ID: {data.sample.sampleId}</p><p>Type: {data.sample.type} · Collected: {data.sample.collectedAt?new Date(data.sample.collectedAt).toLocaleString():'N/A'}</p><p>Adequate: {data.sample.isAdequate?'Yes':'No'}</p>{data.sample.rejectionReason&&<p className="text-red-600">Rejected: {data.sample.rejectionReason}</p>}</div>:<p className="text-gray-400">No sample collected yet</p>}</CardContent></Card></div>)
}
