/**
 * ─── Clinic Pages — Medical Records, Prescriptions, Billing, Inventory, Departments ──
 * All labels in English. Metadata-driven from entity packages.
 */
import React, { useEffect, useState } from 'react'
import { Link, useParams, useNavigate } from '@tanstack/react-router'
import { Card, CardHeader, CardContent, cn } from '@repo/ui-core'
import { Plus, Search, ArrowLeft, Save } from 'lucide-react'
import { medicalRecordRepo, prescriptionRepo, billingRepo, inventoryRepo, departmentRepo } from '../../lib/db'
import { RECORD_TYPE_LABELS, RECORD_STATUS_LABELS } from '@repo/entity-medical-record'
import { PRESCRIPTION_STATUS_LABELS, DOSAGE_FREQUENCY_LABELS } from '@repo/entity-prescription'
import { InvoiceStatusLabels } from '@repo/entity-billing'
import { INVENTORY_CATEGORY_LABELS, INVENTORY_STATUS_LABELS } from '@repo/entity-inventory'
import { DEPARTMENT_TYPE_LABELS } from '@repo/entity-department'

const TENANT_ID = 'default-tenant'

// ─── Medical Record Pages ────────────────────────────────────
export function MedicalRecordListPage() {
  const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true)
  useEffect(()=>{medicalRecordRepo.findMany({limit:100}).then((r:any)=>{setItems('items' in r?r.items:[]);setLoading(false)}).catch(()=>setLoading(false))},[])
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Medical Records</h1><p className="text-sm text-gray-500">{items.length} records</p></div><Link to="/medical-records/new" className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700"><Plus className="h-4 w-4"/>New Record</Link></div>
  {loading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-16 animate-pulse rounded-lg bg-gray-100"/>)}</div>
  :<div className="rounded-lg border bg-white"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr>{['Type','Patient','Doctor','Complaint','Status','Date'].map(l=><th key={l} className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">{l}</th>)}</tr></thead><tbody className="divide-y divide-gray-200">{items.map((r:any)=>(<tr key={r.id} className="cursor-pointer hover:bg-gray-50" onClick={()=>window.location.href=`/medical-records/${r.id}`}><td className="px-4 py-3 text-sm">{RECORD_TYPE_LABELS[r.type]??r.type}</td><td className="px-4 py-3 text-sm text-gray-600">{r.patientId?.slice(0,8)}...</td><td className="px-4 py-3 text-sm text-gray-600">{r.doctorId?.slice(0,8)}...</td><td className="px-4 py-3 text-sm text-gray-600 max-w-[200px] truncate">{r.chiefComplaint}</td><td className="px-4 py-3 text-sm">{RECORD_STATUS_LABELS[r.status]??r.status}</td><td className="px-4 py-3 text-sm text-gray-600">{r.encounterDate?new Date(r.encounterDate).toLocaleDateString():'-'}</td></tr>))}</tbody></table></div>}</div>)
}

export function CreateMedicalRecordPage() {
  const navigate=useNavigate();const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const [form,setForm]=useState({patientId:'',doctorId:'',type:'consultation',chiefComplaint:'',presentIllness:'',physicalExam:'',treatmentPlan:'',followUpInstructions:'',notes:''})
  const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setSaving(true);try{const r=await medicalRecordRepo.create({tenantId:TENANT_ID,patientId:form.patientId,doctorId:form.doctorId,type:form.type,chiefComplaint:form.chiefComplaint,presentIllness:form.presentIllness,physicalExam:form.physicalExam,treatmentPlan:form.treatmentPlan,followUpInstructions:form.followUpInstructions,notes:form.notes,diagnoses:[],vitalSigns:{}} as any);navigate({to:'/medical-records/$id',params:{id:r.id}})}catch(err:any){setError(err.message)}finally{setSaving(false)}}
  return (<div className="p-6"><div className="mb-6 flex items-center gap-4"><button onClick={()=>navigate({to:'/medical-records'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">New Medical Record</h1></div></div>{error&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <form onSubmit={handleSubmit}><Card><CardContent><div className="grid grid-cols-1 gap-4 md:grid-cols-2">
    {[{name:'patientId',label:'Patient ID',type:'text',required:true},{name:'doctorId',label:'Doctor ID',type:'text',required:true},{name:'type',label:'Type',type:'select',options:[{label:'Consultation',value:'consultation'},{label:'Emergency',value:'emergency'},{label:'Follow-up',value:'follow_up'}]},{name:'chiefComplaint',label:'Chief Complaint',type:'textarea',required:true,colSpan:true},{name:'presentIllness',label:'History of Present Illness',type:'textarea',colSpan:true},{name:'physicalExam',label:'Physical Examination',type:'textarea',colSpan:true},{name:'treatmentPlan',label:'Treatment Plan',type:'textarea',colSpan:true},{name:'followUpInstructions',label:'Follow-up Instructions',type:'textarea',colSpan:true},{name:'notes',label:'Notes',type:'textarea',colSpan:true}].map(f=>(<div key={f.name} className={(f as any).colSpan?'col-span-full space-y-1':'space-y-1'}><label className="block text-sm font-medium text-gray-700">{f.label}{f.required&&<span className="text-red-500 ml-1">*</span>}</label>{f.type==='select'?<select value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"><option value="">Select...</option>{f.options?.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} rows={4} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"/>:<input type={f.type} value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"/>}</div>))}
  </div></CardContent></Card><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>navigate({to:'/medical-records'})} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700 disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving...':'Save Record'}</button></div></form></div>)
}

export function MedicalRecordDetailPage() {
  const {id}=useParams({from:'/medical-records/$id'});const navigate=useNavigate();const [data,setData]=useState<any>(null)
  useEffect(()=>{medicalRecordRepo.findById(id).then(setData).catch(console.error)},[id])
  if(!data) return <div className="flex h-full items-center justify-center"><div className="text-center"><h2 className="text-2xl font-semibold">Record Not Found</h2><button onClick={()=>navigate({to:'/medical-records'})} className="mt-4 rounded-lg bg-red-600 px-4 py-2 text-sm text-white">Back</button></div></div>
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-4"><button onClick={()=>navigate({to:'/medical-records'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">{RECORD_TYPE_LABELS[data.type]??data.type}</h1><p className="text-sm text-gray-500">{data.encounterDate?new Date(data.encounterDate).toLocaleString('en-US',{dateStyle:'long'}):''}</p></div></div><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-medium text-blue-800">{RECORD_STATUS_LABELS[data.status]??data.status}</span></div>
  <Card><CardHeader title="Clinical Information"/><CardContent><dl className="divide-y divide-gray-100">{[{l:'Chief Complaint',k:'chiefComplaint'},{l:'History of Present Illness',k:'presentIllness'},{l:'Physical Examination',k:'physicalExam'},{l:'Diagnoses',k:'diagnoses'},{l:'Treatment Plan',k:'treatmentPlan'},{l:'Follow-up Instructions',k:'followUpInstructions'},{l:'Notes',k:'notes'}].map(f=>(<div key={f.k} className="py-3"><dt className="text-sm font-medium text-gray-500">{f.l}</dt><dd className="mt-1 text-sm text-gray-900 whitespace-pre-wrap">{f.k==='diagnoses'?Array.isArray(data[f.k])?data[f.k].map((d:any)=>`${d.code} - ${d.description} (${d.type})`).join('\n'):'-':String(data[f.k]??'-')}</dd></div>))}</dl></CardContent></Card></div>)
}

// ─── Prescription Pages ──────────────────────────────────────
export function PrescriptionListPage() {
  const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true)
  useEffect(()=>{prescriptionRepo.findMany({limit:100}).then((r:any)=>{setItems('items' in r?r.items:[]);setLoading(false)}).catch(()=>setLoading(false))},[])
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Prescriptions</h1><p className="text-sm text-gray-500">{items.length} prescriptions</p></div><Link to="/prescriptions/new" className="inline-flex items-center gap-2 rounded-lg bg-yellow-600 px-4 py-2 text-sm font-medium text-white hover:bg-yellow-700"><Plus className="h-4 w-4"/>New Prescription</Link></div>
  {loading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-16 animate-pulse rounded-lg bg-gray-100"/>)}</div>
  :<div className="rounded-lg border bg-white"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr>{['Patient','Doctor','Medications','Status','Date'].map(l=><th key={l} className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">{l}</th>)}</tr></thead><tbody className="divide-y divide-gray-200">{items.map((r:any)=>(<tr key={r.id} className="cursor-pointer hover:bg-gray-50" onClick={()=>window.location.href=`/prescriptions/${r.id}`}><td className="px-4 py-3 text-sm text-gray-600">{r.patientId?.slice(0,8)}...</td><td className="px-4 py-3 text-sm text-gray-600">{r.doctorId?.slice(0,8)}...</td><td className="px-4 py-3 text-sm text-gray-600">{r.medications?.map((m:any)=>m.name).join(', ').slice(0,50)}</td><td className="px-4 py-3 text-sm">{PRESCRIPTION_STATUS_LABELS[r.status]??r.status}</td><td className="px-4 py-3 text-sm text-gray-600">{r.startDate?new Date(r.startDate).toLocaleDateString():'-'}</td></tr>))}</tbody></table></div>}</div>)
}

export function CreatePrescriptionPage() {
  const navigate=useNavigate();const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const [form,setForm]=useState({patientId:'',doctorId:'',medications:'[{"name":"Paracetamol","strength":"500mg","form":"Tablet","dosage":"1 tablet","frequency":"three_times_daily","route":"oral","durationDays":7,"quantity":21,"allowGeneric":true,"refills":0,"isControlled":false}]',diagnosis:'',notes:''})
  const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setSaving(true);try{let meds;try{meds=JSON.parse(form.medications)}catch{meds=[{name:form.medications,strength:'',form:'',dosage:'',frequency:'once_daily',route:'oral',durationDays:7,quantity:1,allowGeneric:true,refills:0,isControlled:false}]};const r=await prescriptionRepo.create({tenantId:TENANT_ID,patientId:form.patientId,doctorId:form.doctorId,medications:meds,diagnosis:form.diagnosis,notes:form.notes} as any);navigate({to:'/prescriptions/$id',params:{id:r.id}})}catch(err:any){setError(err.message)}finally{setSaving(false)}}
  return (<div className="p-6"><div className="mb-6 flex items-center gap-4"><button onClick={()=>navigate({to:'/prescriptions'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">New Prescription</h1></div></div>{error&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <form onSubmit={handleSubmit}><Card><CardContent><div className="grid grid-cols-1 gap-4 md:grid-cols-2">{[{name:'patientId',label:'Patient ID',type:'text',required:true},{name:'doctorId',label:'Doctor ID',type:'text',required:true},{name:'medications',label:'Medications (JSON)',type:'textarea',required:true,helper:'JSON array of medications'},{name:'diagnosis',label:'Diagnosis',type:'text'},{name:'notes',label:'Notes',type:'textarea'}].map(f=>(<div key={f.name} className={(f.name==='medications'||f.name==='notes')?'col-span-full space-y-1':'space-y-1'}><label className="block text-sm font-medium text-gray-700">{f.label}{f.required&&<span className="text-red-500 ml-1">*</span>}</label>{f.type==='textarea'?<textarea value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} rows={f.name==='medications'?6:3} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm font-mono"/>:<input type={f.type} value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"/>}{(f as any).helper&&<p className="text-xs text-gray-500">{(f as any).helper}</p>}</div>))}</div></CardContent></Card><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>navigate({to:'/prescriptions'})} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-yellow-600 px-4 py-2 text-sm font-medium text-white hover:bg-yellow-700 disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving...':'Save Prescription'}</button></div></form></div>)
}

export function PrescriptionDetailPage() {
  const {id}=useParams({from:'/prescriptions/$id'});const navigate=useNavigate();const [data,setData]=useState<any>(null)
  useEffect(()=>{prescriptionRepo.findById(id).then(setData).catch(console.error)},[id])
  if(!data) return <div className="flex h-full items-center justify-center"><div className="text-center"><h2 className="text-2xl font-semibold">Prescription Not Found</h2><button onClick={()=>navigate({to:'/prescriptions'})} className="mt-4 rounded-lg bg-yellow-600 px-4 py-2 text-sm text-white">Back</button></div></div>
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-4"><button onClick={()=>navigate({to:'/prescriptions'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">Medical Prescription</h1><p className="text-sm text-gray-500">{data.startDate?new Date(data.startDate).toLocaleDateString('en-US',{dateStyle:'long'}):''}</p></div></div><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-medium text-blue-800">{PRESCRIPTION_STATUS_LABELS[data.status]??data.status}</span></div>
  <div className="space-y-4"><Card><CardHeader title="Medications"/><CardContent><div className="space-y-3">{data.medications?.map((m:any,i:number)=>(<div key={i} className="rounded-lg border border-gray-200 p-4"><p className="font-medium text-gray-900">{m.name} {m.strength} - {m.form}</p><p className="text-sm text-gray-600 mt-1">Dosage: {m.dosage} | {DOSAGE_FREQUENCY_LABELS[m.frequency]??m.frequency} | {m.route} | {m.durationDays} days | Qty: {m.quantity}</p>{m.instructions&&<p className="text-sm text-gray-500 mt-1">Instructions: {m.instructions}</p>}{m.isControlled&&<span className="inline-flex mt-2 rounded-full bg-red-100 px-2 py-0.5 text-xs font-medium text-red-800">Controlled Substance</span>}</div>))}</div></CardContent></Card><Card><CardHeader title="Details"/><CardContent><dl className="divide-y divide-gray-100">{[{l:'Diagnosis',k:'diagnosis'},{l:'Total Days',k:'totalDays'},{l:'Notes',k:'notes'},{l:'Drug Interactions',k:'_interactions'}].map(f=>(<div key={f.k} className="flex justify-between py-2"><dt className="text-sm text-gray-500">{f.l}</dt><dd className="text-sm font-medium text-gray-900">{f.k==='_interactions'&&Array.isArray(data[f.k])?data[f.k].length?data[f.k].join('\n'):'None':String(data[f.k]??'-')}</dd></div>))}</dl></CardContent></Card></div></div>)
}

// ─── Billing Pages ───────────────────────────────────────────
export function BillingListPage() {
  const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true)
  useEffect(()=>{billingRepo.findMany({limit:100}).then((r:any)=>{setItems('items' in r?r.items:[]);setLoading(false)}).catch(()=>setLoading(false))},[])
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Billing</h1><p className="text-sm text-gray-500">{items.length} invoices</p></div><Link to="/billing/new" className="inline-flex items-center gap-2 rounded-lg bg-yellow-600 px-4 py-2 text-sm font-medium text-white hover:bg-yellow-700"><Plus className="h-4 w-4"/>New Invoice</Link></div>
  {loading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-16 animate-pulse rounded-lg bg-gray-100"/>)}</div>
  :<div className="rounded-lg border bg-white"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr>{['Invoice #','Patient','Total','Paid','Balance','Status','Date'].map(l=><th key={l} className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">{l}</th>)}</tr></thead><tbody className="divide-y divide-gray-200">{items.map((r:any)=>(<tr key={r.id} className="cursor-pointer hover:bg-gray-50" onClick={()=>window.location.href=`/billing/${r.id}`}><td className="px-4 py-3 text-sm font-medium text-gray-900">{r.invoiceNumber}</td><td className="px-4 py-3 text-sm text-gray-600">{r.patientId?.slice(0,8)}...</td><td className="px-4 py-3 text-sm">${r.totalAmount?.toLocaleString?.()??r.totalAmount}</td><td className="px-4 py-3 text-sm text-green-600">${r.paidAmount?.toLocaleString?.()??r.paidAmount}</td><td className="px-4 py-3 text-sm text-red-600">${r.balanceDue?.toLocaleString?.()??r.balanceDue}</td><td className="px-4 py-3 text-sm">{InvoiceStatusLabels[r.status]??r.status}</td><td className="px-4 py-3 text-sm text-gray-600">{r.issueDate?new Date(r.issueDate).toLocaleDateString():'-'}</td></tr>))}</tbody></table></div>}</div>)
}

export function CreateInvoicePage() {
  const navigate=useNavigate();const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const [form,setForm]=useState({patientId:'',invoiceType:'recibo',items:'[{"id":"1","description":"General Consultation","quantity":1,"unitPrice":500,"total":500,"category":"consultation","taxRate":0.16,"taxExempt":false}]',taxId:'',notes:''})
  const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setSaving(true);try{let items;try{items=JSON.parse(form.items)}catch{items=[{id:'1',description:form.items,quantity:1,unitPrice:0,total:0,category:'other',taxRate:0.16,taxExempt:false}]};const r=await billingRepo.create({tenantId:TENANT_ID,patientId:form.patientId,invoiceType:form.invoiceType,items,taxId:form.taxId,notes:form.notes} as any);navigate({to:'/billing/$id',params:{id:r.id}})}catch(err:any){setError(err.message)}finally{setSaving(false)}}
  return (<div className="p-6"><div className="mb-6 flex items-center gap-4"><button onClick={()=>navigate({to:'/billing'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">New Invoice</h1></div></div>{error&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <form onSubmit={handleSubmit}><Card><CardContent><div className="grid grid-cols-1 gap-4 md:grid-cols-2">{[{name:'patientId',label:'Patient ID',type:'text',required:true},{name:'invoiceType',label:'Invoice Type',type:'select',options:[{label:'Invoice (Factura)',value:'factura'},{label:'Receipt',value:'recibo'},{label:'Sales Note',value:'nota_venta'}]},{name:'taxId',label:'Tax ID / RFC',type:'text'},{name:'items',label:'Line Items (JSON)',type:'textarea',required:true,helper:'[{"id":"1","description":"...","quantity":1,"unitPrice":0,"total":0,"category":"consultation","taxRate":0.16,"taxExempt":false}]'},{name:'notes',label:'Notes',type:'textarea'}].map(f=>(<div key={f.name} className={(f.name==='items'||f.name==='notes')?'col-span-full space-y-1':'space-y-1'}><label className="block text-sm font-medium text-gray-700">{f.label}{f.required&&<span className="text-red-500 ml-1">*</span>}</label>{f.type==='select'?<select value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"><option value="">Select...</option>{f.options?.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} rows={f.name==='items'?6:3} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm font-mono"/>:<input type={f.type} value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"/>}{(f as any).helper&&<p className="text-xs text-gray-500">{(f as any).helper}</p>}</div>))}</div></CardContent></Card><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>navigate({to:'/billing'})} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-yellow-600 px-4 py-2 text-sm font-medium text-white hover:bg-yellow-700 disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving...':'Save Invoice'}</button></div></form></div>)
}

export function InvoiceDetailPage() {
  const {id}=useParams({from:'/billing/$id'});const navigate=useNavigate();const [data,setData]=useState<any>(null)
  useEffect(()=>{billingRepo.findById(id).then(setData).catch(console.error)},[id])
  if(!data) return <div className="flex h-full items-center justify-center"><div className="text-center"><h2 className="text-2xl font-semibold">Invoice Not Found</h2><button onClick={()=>navigate({to:'/billing'})} className="mt-4 rounded-lg bg-yellow-600 px-4 py-2 text-sm text-white">Back</button></div></div>
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-4"><button onClick={()=>navigate({to:'/billing'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">Invoice {data.invoiceNumber}</h1><p className="text-sm text-gray-500">{data.issueDate?new Date(data.issueDate).toLocaleDateString('en-US',{dateStyle:'long'}):''}</p></div></div><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-medium text-blue-800">{InvoiceStatusLabels[data.status]??data.status}</span></div>
  <div className="grid grid-cols-1 gap-6 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader title="Line Items"/><CardContent><table className="min-w-full"><thead><tr className="text-left text-xs text-gray-500"><th className="pb-2">Item</th><th className="pb-2">Qty</th><th className="pb-2">Unit Price</th><th className="pb-2">Total</th></tr></thead><tbody>{data.items?.map((item:any,i:number)=>(<tr key={i} className="border-t border-gray-100"><td className="py-2 text-sm text-gray-900">{item.description}</td><td className="py-2 text-sm">{item.quantity}</td><td className="py-2 text-sm">${item.unitPrice?.toLocaleString?.()??item.unitPrice}</td><td className="py-2 text-sm font-medium">${item.total?.toLocaleString?.()??item.total}</td></tr>))}</tbody></table></CardContent></Card><Card><CardHeader title="Totals"/><CardContent><dl className="space-y-3"><div className="flex justify-between"><dt className="text-sm text-gray-500">Subtotal</dt><dd className="text-sm font-medium">${data.subTotal?.toLocaleString?.()??data.subTotal}</dd></div><div className="flex justify-between"><dt className="text-sm text-gray-500">Tax</dt><dd className="text-sm font-medium">${data.taxAmount?.toLocaleString?.()??data.taxAmount}</dd></div><div className="flex justify-between"><dt className="text-sm text-gray-500">Discount</dt><dd className="text-sm font-medium text-red-600">-${data.discountAmount?.toLocaleString?.()??data.discountAmount}</dd></div><hr/><div className="flex justify-between"><dt className="text-sm font-semibold">Total</dt><dd className="text-lg font-semibold">${data.totalAmount?.toLocaleString?.()??data.totalAmount}</dd></div><div className="flex justify-between"><dt className="text-sm text-green-600">Paid</dt><dd className="text-sm font-medium text-green-600">${data.paidAmount?.toLocaleString?.()??data.paidAmount}</dd></div><div className="flex justify-between"><dt className="text-sm text-red-600">Balance Due</dt><dd className="text-sm font-medium text-red-600">${data.balanceDue?.toLocaleString?.()??data.balanceDue}</dd></div></dl></CardContent></Card></div></div>)
}

// ─── Inventory Pages ─────────────────────────────────────────
export function InventoryListPage() {
  const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true)
  useEffect(()=>{inventoryRepo.findMany({limit:100}).then((r:any)=>{setItems('items' in r?r.items:[]);setLoading(false)}).catch(()=>setLoading(false))},[])
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Inventory</h1><p className="text-sm text-gray-500">{items.length} items</p></div><Link to="/inventory/new" className="inline-flex items-center gap-2 rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700"><Plus className="h-4 w-4"/>New Item</Link></div>
  {loading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-16 animate-pulse rounded-lg bg-gray-100"/>)}</div>
  :<div className="rounded-lg border bg-white"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr>{['Name','Category','Stock','Cost','Supplier','Status'].map(l=><th key={l} className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">{l}</th>)}</tr></thead><tbody className="divide-y divide-gray-200">{items.map((r:any)=>(<tr key={r.id} className="cursor-pointer hover:bg-gray-50" onClick={()=>window.location.href=`/inventory/${r.id}`}><td className="px-4 py-3 text-sm font-medium text-gray-900">{r.name}{r.genericName&&<span className="text-xs text-gray-400 ml-1">({r.genericName})</span>}</td><td className="px-4 py-3 text-sm text-gray-600">{INVENTORY_CATEGORY_LABELS[r.category]??r.category}</td><td className="px-4 py-3 text-sm"><span className={cn('font-medium',r.quantityOnHand<=0?'text-red-600':r.quantityOnHand<=(r.minimumQuantity??10)?'text-yellow-600':'text-green-600')}>{r.quantityOnHand}</span></td><td className="px-4 py-3 text-sm">${r.unitCost?.toLocaleString?.()??r.unitCost}</td><td className="px-4 py-3 text-sm text-gray-600">{r.supplier||'-'}</td><td className="px-4 py-3 text-sm">{INVENTORY_STATUS_LABELS[r.status]??r.status}</td></tr>))}</tbody></table></div>}</div>)
}

export function CreateInventoryItemPage() {
  const navigate=useNavigate();const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const [form,setForm]=useState({name:'',genericName:'',category:'medication',unit:'tablet',sku:'',quantityOnHand:0,minimumQuantity:10,maximumQuantity:100,unitCost:0,sellingPrice:0,supplier:'',lotNumber:'',location:'',notes:''})
  const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setSaving(true);try{const r=await inventoryRepo.create({...form,tenantId:TENANT_ID} as any);navigate({to:'/inventory/$id',params:{id:r.id}})}catch(err:any){setError(err.message)}finally{setSaving(false)}}
  return (<div className="p-6"><div className="mb-6 flex items-center gap-4"><button onClick={()=>navigate({to:'/inventory'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">New Inventory Item</h1></div></div>{error&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <form onSubmit={handleSubmit}><Card><CardContent><div className="grid grid-cols-1 gap-4 md:grid-cols-2">{[{name:'name',label:'Name',type:'text',required:true},{name:'genericName',label:'Generic Name',type:'text'},{name:'category',label:'Category',type:'select',options:Object.entries(INVENTORY_CATEGORY_LABELS).map(([v,l])=>({label:l,value:v}))},{name:'unit',label:'Unit',type:'text'},{name:'sku',label:'SKU / Code',type:'text'},{name:'quantityOnHand',label:'Initial Stock',type:'number'},{name:'minimumQuantity',label:'Min Stock',type:'number'},{name:'maximumQuantity',label:'Max Stock',type:'number'},{name:'unitCost',label:'Unit Cost',type:'number'},{name:'sellingPrice',label:'Selling Price',type:'number'},{name:'supplier',label:'Supplier',type:'text'},{name:'lotNumber',label:'Lot Number',type:'text'},{name:'location',label:'Location',type:'text'},{name:'notes',label:'Notes',type:'textarea'}].map(f=>(<div key={f.name} className={(f.name==='notes')?'col-span-full space-y-1':'space-y-1'}><label className="block text-sm font-medium text-gray-700">{f.label}{f.required&&<span className="text-red-500 ml-1">*</span>}</label>{f.type==='select'?<select value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"><option value="">Select...</option>{f.options?.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} rows={3} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"/>:<input type={f.type} value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:f.type==='number'?Number(e.target.value):e.target.value}))} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"/>}</div>))}</div></CardContent></Card><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>navigate({to:'/inventory'})} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700 disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving...':'Save Item'}</button></div></form></div>)
}

export function InventoryItemDetailPage() {
  const {id}=useParams({from:'/inventory/$id'});const navigate=useNavigate();const [data,setData]=useState<any>(null)
  useEffect(()=>{inventoryRepo.findById(id).then(setData).catch(console.error)},[id])
  if(!data) return <div className="flex h-full items-center justify-center"><div className="text-center"><h2 className="text-2xl font-semibold">Item Not Found</h2><button onClick={()=>navigate({to:'/inventory'})} className="mt-4 rounded-lg bg-green-600 px-4 py-2 text-sm text-white">Back</button></div></div>
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-4"><button onClick={()=>navigate({to:'/inventory'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">{data.name}</h1><p className="text-sm text-gray-500">{data.genericName||''} • {INVENTORY_CATEGORY_LABELS[data.category]??data.category}</p></div></div><span className={cn('rounded-full px-3 py-1 text-xs font-medium',data.status==='in_stock'?'bg-green-100 text-green-800':data.status==='low_stock'?'bg-yellow-100 text-yellow-800':'bg-red-100 text-red-800')}>{INVENTORY_STATUS_LABELS[data.status]??data.status}</span></div>
  <Card><CardHeader title="Details"/><CardContent><dl className="divide-y divide-gray-100">{[{l:'SKU',k:'sku'},{l:'Current Stock',k:'quantityOnHand'},{l:'Min Stock',k:'minimumQuantity'},{l:'Max Stock',k:'maximumQuantity'},{l:'Unit Cost',k:'unitCost'},{l:'Selling Price',k:'sellingPrice'},{l:'Supplier',k:'supplier'},{l:'Lot',k:'lotNumber'},{l:'Location',k:'location'},{l:'Expiration',k:'expirationDate'},{l:'Controlled',k:'isControlled'},{l:'Notes',k:'notes'}].map(f=>(<div key={f.k} className="flex justify-between py-2"><dt className="text-sm text-gray-500">{f.l}</dt><dd className="text-sm font-medium text-gray-900">{f.k==='expirationDate'&&data[f.k]?new Date(data[f.k]).toLocaleDateString():f.k==='isControlled'?(data[f.k]?'Yes':'No'):typeof data[f.k]==='number'&&(f.k==='unitCost'||f.k==='sellingPrice')?`$${data[f.k]?.toLocaleString?.()??data[f.k]}`:String(data[f.k]??'-')}</dd></div>))}</dl></CardContent></Card></div>)
}

// ─── Department Pages ────────────────────────────────────────
export function DepartmentListPage() {
  const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true)
  useEffect(()=>{departmentRepo.findMany({limit:100}).then((r:any)=>{setItems('items' in r?r.items:[]);setLoading(false)}).catch(()=>setLoading(false))},[])
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Departments</h1><p className="text-sm text-gray-500">{items.length} departments</p></div><Link to="/departments/new" className="inline-flex items-center gap-2 rounded-lg bg-purple-600 px-4 py-2 text-sm font-medium text-white hover:bg-purple-700"><Plus className="h-4 w-4"/>New Dept</Link></div>
  {loading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-16 animate-pulse rounded-lg bg-gray-100"/>)}</div>
  :<div className="rounded-lg border bg-white"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr>{['Code','Name','Type','Floor','Extension','Active'].map(l=><th key={l} className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">{l}</th>)}</tr></thead><tbody className="divide-y divide-gray-200">{items.map((r:any)=>(<tr key={r.id} className="cursor-pointer hover:bg-gray-50" onClick={()=>window.location.href=`/departments/${r.id}`}><td className="px-4 py-3 text-sm font-medium text-gray-900">{r.code}</td><td className="px-4 py-3 text-sm text-gray-900">{r.name}</td><td className="px-4 py-3 text-sm text-gray-600">{DEPARTMENT_TYPE_LABELS[r.type]??r.type}</td><td className="px-4 py-3 text-sm text-gray-600">{r.floor||'-'}</td><td className="px-4 py-3 text-sm text-gray-600">{r.phoneExtension||'-'}</td><td className="px-4 py-3 text-sm">{r.isActive?'Active':'Inactive'}</td></tr>))}</tbody></table></div>}</div>)
}

export function CreateDepartmentPage() {
  const navigate=useNavigate();const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const [form,setForm]=useState({name:'',code:'',type:'clinical',description:'',floor:'',building:'',phoneExtension:'',operatingHoursStart:'08:00',operatingHoursEnd:'17:00',is24x7:false,roomCount:1,notes:''})
  const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setSaving(true);try{const r=await departmentRepo.create({...form,tenantId:TENANT_ID,isActive:true} as any);navigate({to:'/departments/$id',params:{id:r.id}})}catch(err:any){setError(err.message)}finally{setSaving(false)}}
  return (<div className="p-6"><div className="mb-6 flex items-center gap-4"><button onClick={()=>navigate({to:'/departments'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">New Department</h1></div></div>{error&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <form onSubmit={handleSubmit}><Card><CardContent><div className="grid grid-cols-1 gap-4 md:grid-cols-2">{[{name:'name',label:'Name',type:'text',required:true},{name:'code',label:'Code',type:'text',required:true},{name:'type',label:'Type',type:'select',options:Object.entries(DEPARTMENT_TYPE_LABELS).map(([v,l])=>({label:l,value:v}))},{name:'description',label:'Description',type:'text'},{name:'floor',label:'Floor',type:'text'},{name:'building',label:'Building',type:'text'},{name:'phoneExtension',label:'Phone Ext.',type:'text'},{name:'operatingHoursStart',label:'Hours Start',type:'text'},{name:'operatingHoursEnd',label:'Hours End',type:'text'},{name:'is24x7',label:'24/7',type:'text'},{name:'roomCount',label:'Rooms',type:'number'},{name:'notes',label:'Notes',type:'textarea'}].map(f=>(<div key={f.name} className={(f.name==='notes')?'col-span-full space-y-1':'space-y-1'}><label className="block text-sm font-medium text-gray-700">{f.label}{f.required&&<span className="text-red-500 ml-1">*</span>}</label>{f.type==='select'?<select value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"><option value="">Select...</option>{f.options?.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:e.target.value}))} rows={3} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"/>:<input type={f.type} value={(form as any)[f.name]??''} onChange={e=>setForm(p=>({...p,[f.name]:f.type==='number'?Number(e.target.value):e.target.value}))} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"/>}</div>))}</div></CardContent></Card><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>navigate({to:'/departments'})} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-purple-600 px-4 py-2 text-sm font-medium text-white hover:bg-purple-700 disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving...':'Save Dept'}</button></div></form></div>)
}

export function DepartmentDetailPage() {
  const {id}=useParams({from:'/departments/$id'});const navigate=useNavigate();const [data,setData]=useState<any>(null)
  useEffect(()=>{departmentRepo.findById(id).then(setData).catch(console.error)},[id])
  if(!data) return <div className="flex h-full items-center justify-center"><div className="text-center"><h2 className="text-2xl font-semibold">Dept Not Found</h2><button onClick={()=>navigate({to:'/departments'})} className="mt-4 rounded-lg bg-purple-600 px-4 py-2 text-sm text-white">Back</button></div></div>
  return (<div className="p-6"><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-4"><button onClick={()=>navigate({to:'/departments'})} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-semibold">{data.name} <span className="text-sm text-gray-400">({data.code})</span></h1><p className="text-sm text-gray-500">{DEPARTMENT_TYPE_LABELS[data.type]??data.type}</p></div></div><span className={cn('rounded-full px-3 py-1 text-xs font-medium',data.isActive?'bg-green-100 text-green-800':'bg-red-100 text-red-800')}>{data.isActive?'Active':'Inactive'}</span></div>
  <Card><CardHeader title="Information"/><CardContent><dl className="divide-y divide-gray-100">{[{l:'Description',k:'description'},{l:'Floor',k:'floor'},{l:'Building',k:'building'},{l:'Extension',k:'phoneExtension'},{l:'Hours',k:'operatingHoursStart'},{l:'24/7',k:'is24x7'},{l:'Rooms',k:'roomCount'},{l:'Notes',k:'notes'}].map(f=>(<div key={f.k} className="flex justify-between py-2"><dt className="text-sm text-gray-500">{f.l}</dt><dd className="text-sm font-medium text-gray-900">{f.k==='operatingHoursStart'?`${data.operatingHoursStart??'08:00'} - ${data.operatingHoursEnd??'17:00'}`:f.k==='is24x7'?(data[f.k]?'Yes':'No'):String(data[f.k]??'-')}</dd></div>))}</dl></CardContent></Card></div>)
}
